/**
 * Generates `dist/tokens.css` from the token source of truth.
 *
 * `dist/tokens.css` IS committed (consumers import it before this package is
 * built). Run `pnpm --filter @line-os/tokens build:css` after changing any
 * token; `tokens.test.ts` fails if the committed file is stale.
 */
// Run with: node --import tsx scripts/build-css.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const { flatTokens } = await import('../src/index.ts');

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'dist', 'tokens.css');

const body = Object.entries(flatTokens)
  .map(([name, value]) => `  ${name}: ${value};`)
  .join('\n');

const css = `/*
 * ORUWA design tokens — GENERATED by packages/tokens/scripts/build-css.mjs.
 * Do not edit by hand. Source of truth: packages/tokens/src/{primitives,semantic}.ts
 */
:root {
${body}
}
`;

writeFileSync(outPath, css, 'utf8');
console.log(`wrote ${outPath} (${Object.keys(flatTokens).length} tokens)`);
